apiVersion: v1
data:
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: server-profiles/pingdirectory
  SERVER_PROFILE_URL: https://github.com/mdeller-ping/poc-segra.git
kind: ConfigMap
metadata:
  labels:
    role: pingdirectory
  name: pingdirectory-environment-variables
